<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\Service\RenderService;

/** @var RenderService $this */
/** @var array<string, mixed> $vars */

?>
<div class="card mt-5">
    <div class="card-header">
        <p class="card-header-title">
            <?= $this->text('text.change-password') ?>
        </p>
    </div>
    <div class="card-content">
        <div class="content">
            <form action="/admin/change-password" method="POST">
                <div class="field">
                    <p class="control">
                        <label for="password" aria-hidden="true" style="display: none"><?= $this->text('label.password') ?></label>
                        <input name="password" id="password" class="input" type="password" placeholder="<?= $this->text('label.password') ?>" required>
                    </p>
                </div>
                <div class="field">
                    <p class="control">
                        <button class="button is-danger is-rounded" type="submit">
                            <?= $this->text('button.change') ?>
                        </button>
                    </p>
                </div>
            </form>
        </div>
    </div>
</div>
