<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\Service\RenderService;

/** @var RenderService $this */
/** @var array<string, mixed> $vars */

/** @var string $domainName */
$domainName = $vars['domainName'];

?>
<div class="card">
    <div class="card-header">
        <p class="card-header-title">
            <?= $this->text('text.domain-name') ?>
        </p>
    </div>
    <div class="card-content">
        <div class="content">
            <form action="/admin/change-domain-name" method="POST">
                <div class="field">
                    <p class="control">
                        <label for="domain-name" aria-hidden="true" style="display: none"><?= $this->text('label.domain-name') ?></label>
                        <input name="domain-name" id="domain-name" class="input" type="text" value="<?= $this->text($domainName) ?>" required>
                    </p>
                </div>
                <div class="field">
                    <p class="control">
                        <button class="button is-danger is-rounded" type="submit">
                            <?= $this->text('button.change') ?>
                        </button>
                    </p>
                </div>
            </form>
        </div>
    </div>
</div>
