<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\Service\RenderService;

/** @var RenderService $this */
/** @var array<string, mixed> $vars */

?>
<div class="card mt-5">
    <div class="card-header">
        <p class="card-header-title">
            System information
        </p>
    </div>
    <div class="card-content">
        <div class="content has-text-centered">
            Hello World
        </div>
    </div>
</div>
