<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\Service\RenderService;

/** @var RenderService $this */
/** @var array<string, mixed> $vars */

$this->setTitle('title.admin');

?>
<main class="container mt-0 mb-5">
    <h1 class="is-size-1">
        <?= $this->text('title.admin') ?>
    </h1>

    <?php require __DIR__ . '/_change-domain-name.phtml' ?>
    <?php require __DIR__ . '/_change-password.phtml' ?>
    <?php require __DIR__ . '/_bearer-token.phtml' ?>
    <?php require __DIR__ . '/_reset-action-freewar.phtml' ?>
    <?php require __DIR__ . '/_system-information.phtml' ?>
</main>
