<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\Model\PlayerNameHistory;
use Jesperbeisner\Fwstats\Service\ViewRenderService;

/** @var ViewRenderService $this */
/** @var PlayerNameHistory[] $nameChanges */

?>
<div class="card mt-5">
    <div class="card-header">
        <p class="card-header-title">
            Namensänderungen
        </p>
    </div>
    <div class="card-content">
        <div class="content">
            <?php if (count($nameChanges) > 0): ?>
                <div class="table-container">
                    <table class="table is-hoverable is-fullwidth">
                        <thead>
                        <tr>
                            <td>Alter Name</td>
                            <td>Neuer Name</td>
                            <td>Datum</td>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($nameChanges as $nameChange): ?>
                            <tr>
                                <td><?= $nameChange->oldName ?></td>
                                <td><?= $nameChange->newName ?></td>
                                <td><?= $nameChange->created->format('d.m.Y') ?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            <?php else: ?>
                <p class="has-text-centered">
                    Keine Namensänderungen vorhanden.
                </p>
            <?php endif; ?>
        </div>
    </div>
</div>
