<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\Model\PlayerNameHistory;
use Jesperbeisner\Fwstats\Service\RenderService;

/** @var RenderService $this */
/** @var PlayerNameHistory[] $nameChanges */

?>
<div class="card mt-5">
    <div class="card-header">
        <p class="card-header-title">
            <?= $this->text('title.name-changes') ?>
        </p>
    </div>
    <div class="card-content">
        <div class="content">
            <?php if ($nameChanges !== []): ?>
                <div class="table-container">
                    <table class="table is-hoverable is-fullwidth">
                        <thead>
                        <tr>
                            <td><?= $this->text('table.new-name') ?></td>
                            <td><?= $this->text('table.old-name') ?></td>
                            <td><?= $this->text('table.date') ?></td>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($nameChanges as $nameChange): ?>
                            <tr>
                                <td>
                                    <?= $this->escape($nameChange->newName) ?>
                                </td>
                                <td>
                                    <?= $this->escape($nameChange->oldName) ?>
                                </td>
                                <td title="<?= $nameChange->created->format('d.m.Y H:i:s') ?>">
                                    <?= $nameChange->created->format('d.m.Y') ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            <?php else: ?>
                <p class="has-text-centered">
                    <?= $this->text('text.no-name-changes-available') ?>
                </p>
            <?php endif; ?>
        </div>
    </div>
</div>
