<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\DTO\Playtime;
use Jesperbeisner\Fwstats\Service\RenderService;

/** @var RenderService $this */
/** @var array<string, null|Playtime> $weeklyPlaytimes */
/** @var Playtime $totalPlaytime */
/** @var Playtime $averagePlaytime */

?>
<div class="card">
    <div class="card-header">
        <p class="card-header-title">
            <?= $this->text('text.playtime-last-7-days') ?>
        </p>
    </div>
    <div class="card-content">
        <div class="content">
            <div class="table-container">
                <table class="table is-hoverable is-fullwidth">
                    <thead>
                    <tr>
                        <td class="has-text-centered"><?= $this->text('table.hours') ?></td>
                        <td class="has-text-centered"><?= $this->text('table.minutes') ?></td>
                        <td class="has-text-centered"><?= $this->text('table.seconds') ?></td>
                        <td class="has-text-centered"><?= $this->text('table.date') ?></td>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $date = new DateTime('+1 day') ?>
                    <?php foreach ($weeklyPlaytimes as $playtime): ?>
                        <tr>
                            <td class="has-text-centered"><?= $playtime === null ? '-' : $playtime->getHours() ?></td>
                            <td class="has-text-centered"><?= $playtime === null ? '-' : $playtime->getMinutes() ?></td>
                            <td class="has-text-centered"><?= $playtime === null ? '-' : $playtime->getSeconds() ?></td>
                            <td class="has-text-centered"><?= $date->modify('-1 day')->format('d.m.Y') ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <footer class="card-footer">
        <p class="card-footer-item">
            <?= $this->text('text.total') ?>: <?= $totalPlaytime->getHours() ?> h <?= $totalPlaytime->getMinutes() ?> m <?= $totalPlaytime->getSeconds() ?> s
        </p>
        <p class="card-footer-item">
            <?= $this->text('text.on-average') ?>: <?= $averagePlaytime->getHours() ?> h <?= $averagePlaytime->getMinutes() ?> m <?= $averagePlaytime->getSeconds() ?> s
        </p>
    </footer>
</div>
