<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\Model\PlayerProfessionHistory;
use Jesperbeisner\Fwstats\Service\RenderService;

/** @var RenderService $this */
/** @var array<PlayerProfessionHistory> $professionChanges */

?>
<div class="card mt-5">
    <div class="card-header">
        <p class="card-header-title">
            <?= $this->text('title.profession-changes') ?>
        </p>
    </div>
    <div class="card-content">
        <div class="content">
            <?php if ($professionChanges !== []): ?>
                <div class="table-container">
                    <table class="table is-hoverable is-fullwidth">
                        <thead>
                        <tr>
                            <td><?= $this->text('table.old-profession') ?></td>
                            <td><?= $this->text('table.new-profession') ?></td>
                            <td><?= $this->text('table.date') ?></td>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($professionChanges as $professionChange): ?>
                            <tr>
                                <td>
                                    <?= $this->text($professionChange->oldProfession ?? '-') ?>
                                </td>
                                <td>
                                    <?= $this->text($professionChange->newProfession ?? '-') ?>

                                </td>
                                <td title="<?= $professionChange->created->format('d.m.Y H:i:s') ?>">
                                    <?= $professionChange->created->format('d.m.Y') ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            <?php else: ?>
                <p class="has-text-centered">
                    <?= $this->text('text.no-profession-changes-available') ?>
                </p>
            <?php endif; ?>
        </div>
    </div>
</div>
