<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\Model\PlayerProfessionHistory;
use Jesperbeisner\Fwstats\Service\ViewRenderService;

/** @var ViewRenderService $this */
/** @var PlayerProfessionHistory[] $professionChanges */

?>
<div class="card mt-5 mb-5">
    <div class="card-header">
        <p class="card-header-title">
            Berufsänderungen
        </p>
    </div>
    <div class="card-content">
        <div class="content">
            <?php if (count($professionChanges) > 0): ?>
                <div class="table-container">
                    <table class="table is-hoverable is-fullwidth">
                        <thead>
                        <tr>
                            <td>Alter Beruf</td>
                            <td>Neuer Beruf</td>
                            <td>Datum</td>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($professionChanges as $professionChange): ?>
                            <tr>
                                <td><?= $professionChange->oldProfession ?? '-' ?></td>
                                <td><?= $professionChange->newProfession ?? '-' ?></td>
                                <td><?= $professionChange->created->format('d.m.Y') ?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            <?php else: ?>
                <p class="has-text-centered">
                    Keine Berufsänderungen vorhanden.
                </p>
            <?php endif; ?>
        </div>
    </div>
</div>
