<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\Model\PlayerRaceHistory;
use Jesperbeisner\Fwstats\Service\RenderService;

/** @var RenderService $this */
/** @var PlayerRaceHistory[] $raceChanges */

?>

<div class="card mt-5">
    <div class="card-header">
        <p class="card-header-title">
            <?= $this->text('title.race-changes') ?>
        </p>
    </div>
    <div class="card-content">
        <div class="content">
            <?php if ($raceChanges !== []): ?>
                <div class="table-container">
                    <table class="table is-hoverable is-fullwidth">
                        <thead>
                        <tr>
                            <td><?= $this->text('table.old-race') ?></td>
                            <td><?= $this->text('table.new-race') ?></td>
                            <td><?= $this->text('table.date') ?></td>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($raceChanges as $raceChange): ?>
                            <tr>
                                <td>
                                    <?= $this->text($raceChange->oldRace) ?>
                                </td>
                                <td>
                                    <?= $this->text($raceChange->newRace) ?>

                                </td>
                                <td title="<?= $raceChange->created->format('d.m.Y H:i:s') ?>">
                                    <?= $raceChange->created->format('d.m.Y') ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            <?php else: ?>
                <p class="has-text-centered">
                    <?= $this->text('text.no-race-changes-available') ?>
                </p>
            <?php endif; ?>
        </div>
    </div>
</div>
