<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\DTO\Playtime;
use Jesperbeisner\Fwstats\Helper\Html;
use Jesperbeisner\Fwstats\Model\Player;
use Jesperbeisner\Fwstats\Service\ViewRenderService;

/** @var ViewRenderService $this */

/** @var Player $player */
$player = $this->vars['player'];

/** @var array{
 *     day_1: Playtime|null,
 *     day_2: Playtime|null,
 *     day_3: Playtime|null,
 *     day_4: Playtime|null,
 *     day_5: Playtime|null,
 *     day_6: Playtime|null,
 *     day_7: Playtime|null
 * } $playtime
 */
$playtime = $this->vars['playtime'];

$total = 0;
$nullValues = 0;
foreach ($playtime as $time) {
    if ($time !== null) {
        $total += $time->getHours() * 60 * 60;
        $total += $time->getMinutes() * 60;
        $total += $time->getSeconds();
    } else {
        $nullValues++;
    }
}

$totalPlaytime = new Playtime($player->world, $player->name, $player->playerId, $total);
$averagePlaytime = new Playtime($player->world, $player->name, $player->playerId, (int) ($total / (7 - $nullValues)));

$date = new DateTime();

$this->setTitle($player->name . ' - ' . $player->world->worldString());
?>

<div id="profile">
    <h1 class="title is-2">
        <a href="https://<?= $player->world->value ?>.freewar.de/freewar/internal/fight.php?action=watchuser&act_user_id=<?= $player->playerId ?>" target="_blank" class="player_profile_link">
            <?= Html::escape($player->name) ?>
        </a>
    </h1>

    <div class="card">
        <div class="card-header">
            <p class="card-header-title">
                Spielzeit der letzten 7 Tage
            </p>
        </div>
        <div class="card-content">
            <div class="content">
                <div class="table-container">
                    <table class="table is-hoverable is-fullwidth">
                        <thead>
                        <tr>
                            <td>Datum</td>
                            <td>Stunden</td>
                            <td>Minuten</td>
                            <td>Sekunden</td>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td><?= $date->format('d.m.Y') ?></td>
                            <td><?= $playtime['day_1'] === null ? '-' : $playtime['day_1']->getHours() ?></td>
                            <td><?= $playtime['day_1'] === null ? '-' : $playtime['day_1']->getMinutes() ?></td>
                            <td><?= $playtime['day_1'] === null ? '-' : $playtime['day_1']->getSeconds() ?></td>
                        </tr>
                        <tr>
                            <td><?= $date->modify('-1 day')->format('d.m.Y') ?></td>
                            <td><?= $playtime['day_2'] === null ? '-' : $playtime['day_2']->getHours() ?></td>
                            <td><?= $playtime['day_2'] === null ? '-' : $playtime['day_2']->getMinutes() ?></td>
                            <td><?= $playtime['day_2'] === null ? '-' : $playtime['day_2']->getSeconds() ?></td>
                        </tr>
                        <tr>
                            <td><?= $date->modify('-1 day')->format('d.m.Y') ?></td>
                            <td><?= $playtime['day_3'] === null ? '-' : $playtime['day_3']->getHours() ?></td>
                            <td><?= $playtime['day_3'] === null ? '-' : $playtime['day_3']->getMinutes() ?></td>
                            <td><?= $playtime['day_3'] === null ? '-' : $playtime['day_3']->getSeconds() ?></td>
                        </tr>
                        <tr>
                            <td><?= $date->modify('-1 day')->format('d.m.Y') ?></td>
                            <td><?= $playtime['day_4'] === null ? '-' : $playtime['day_4']->getHours() ?></td>
                            <td><?= $playtime['day_4'] === null ? '-' : $playtime['day_4']->getMinutes() ?></td>
                            <td><?= $playtime['day_4'] === null ? '-' : $playtime['day_4']->getSeconds() ?></td>
                        </tr>
                        <tr>
                            <td><?= $date->modify('-1 day')->format('d.m.Y') ?></td>
                            <td><?= $playtime['day_5'] === null ? '-' : $playtime['day_5']->getHours() ?></td>
                            <td><?= $playtime['day_5'] === null ? '-' : $playtime['day_5']->getMinutes() ?></td>
                            <td><?= $playtime['day_5'] === null ? '-' : $playtime['day_5']->getSeconds() ?></td>
                        </tr>
                        <tr>
                            <td><?= $date->modify('-1 day')->format('d.m.Y') ?></td>
                            <td><?= $playtime['day_6'] === null ? '-' : $playtime['day_6']->getHours() ?></td>
                            <td><?= $playtime['day_6'] === null ? '-' : $playtime['day_6']->getMinutes() ?></td>
                            <td><?= $playtime['day_6'] === null ? '-' : $playtime['day_6']->getSeconds() ?></td>
                        </tr>
                        <tr>
                            <td><?= $date->modify('-1 day')->format('d.m.Y') ?></td>
                            <td><?= $playtime['day_7'] === null ? '-' : $playtime['day_7']->getHours() ?></td>
                            <td><?= $playtime['day_7'] === null ? '-' : $playtime['day_7']->getMinutes() ?></td>
                            <td><?= $playtime['day_7'] === null ? '-' : $playtime['day_7']->getSeconds() ?></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <footer class="card-footer">
            <p class="card-footer-item">
                Gesamt: <?= $totalPlaytime->getHours() ?> h <?= $totalPlaytime->getMinutes() ?> m <?= $totalPlaytime->getSeconds() ?> s
            </p>
            <p class="card-footer-item">
                Im Durchschnitt: <?= $averagePlaytime->getHours() ?> h <?= $averagePlaytime->getMinutes() ?> m <?= $averagePlaytime->getSeconds() ?> s
            </p>
        </footer>
    </div>
</div>
