<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\DTO\Playtime;
use Jesperbeisner\Fwstats\Helper\Html;
use Jesperbeisner\Fwstats\Model\Player;
use Jesperbeisner\Fwstats\Service\ViewRenderService;

/** @var ViewRenderService $this */

/** @var Player $player */
$player = $this->vars['player'];

/** @var array<string, Playtime|null> $weeklyPlaytimes */
$weeklyPlaytimes = $this->vars['weeklyPlaytimes'];

/** @var Playtime $totalPlaytime */
$totalPlaytime = $this->vars['totalPlaytime'];

/** @var Playtime $averagePlaytime */
$averagePlaytime = $this->vars['averagePlaytime'];

$this->setTitle($player->name . ' - ' . $player->world->worldString());

?>
<div id="profile">
    <h1 class="title is-2">
        <a href="https://<?= $player->world->value ?>.freewar.de/freewar/internal/fight.php?action=watchuser&act_user_id=<?= $player->playerId ?>" target="_blank" class="player_profile_link">
            <?= Html::escape($player->name) ?>
        </a>
    </h1>

    <div class="card">
        <div class="card-header">
            <p class="card-header-title">
                Spielzeit der letzten 7 Tage
            </p>
        </div>
        <div class="card-content">
            <div class="content">
                <div class="table-container">
                    <table class="table is-hoverable is-fullwidth">
                        <thead>
                        <tr>
                            <td>Datum</td>
                            <td>Stunden</td>
                            <td>Minuten</td>
                            <td>Sekunden</td>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $date = new DateTime('+1 day') ?>
                        <?php foreach ($weeklyPlaytimes as $playtime): ?>
                            <tr>
                                <td><?= $date->modify('-1 day')->format('d.m.Y') ?></td>
                                <td><?= $playtime === null ? '-' : $playtime->getHours() ?></td>
                                <td><?= $playtime === null ? '-' : $playtime->getMinutes() ?></td>
                                <td><?= $playtime === null ? '-' : $playtime->getSeconds() ?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <footer class="card-footer">
            <p class="card-footer-item">
                Gesamt: <?= $totalPlaytime->getHours() ?> h <?= $totalPlaytime->getMinutes() ?> m <?= $totalPlaytime->getSeconds() ?> s
            </p>
            <p class="card-footer-item">
                Im Durchschnitt: <?= $averagePlaytime->getHours() ?> h <?= $averagePlaytime->getMinutes() ?> m <?= $averagePlaytime->getSeconds() ?> s
            </p>
        </footer>
    </div>
</div>
