version: '3.9'

services:
  web:
    image: caddy:2.5.2-alpine
    container_name: fwstats-caddy-prod
    volumes:
      - .:/var/www/html
      - ./.docker/caddy:/etc/caddy
    ports:
      - '8200:80'
    restart: always

  php:
    build:
      dockerfile: .docker/php/Dockerfile-prod
      context: .
    container_name: fwstats-php-prod
    volumes:
      - .:/var/www/html
    restart: always