version: '3.9'

services:
  web:
    image: caddy:2.5.2-alpine
    container_name: fwstats-caddy-dev
    volumes:
      - .:/var/www/html
      - ./.docker/caddy:/etc/caddy
    ports:
      - '8080:80'

  php:
    build: ./.docker/php
    container_name: fwstats-php-dev
    volumes:
      - .:/var/www/html