<form method="POST">
    <div class="field">
        <label class="label" for="email">E-Mail</label>
        <div class="control">
            <input class="input" type="email" name="email" id="email" required>
        </div>
    </div>

    <div class="field">
        <label class="label" for="password">Passwort</label>
        <div class="control">
            <input class="input" type="password" name="password" id="password" required>
        </div>
    </div>

    <div class="control">
        <button class="button is-primary">Login</button>
    </div>
</form>
