<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\Service\RenderService;

/** @var RenderService $this */
/** @var array<string, mixed> $vars */

$this->setTitle('title.login');

?>
<main class="container mt-0 mb-5">
    <h1 class="is-size-1">
        <?= $this->text('title.login') ?>
    </h1>
    <div class="card">
        <div class="card-content">
            <div class="content">
                <div class="columns">
                    <div class="column is-6 is-offset-3">
                        <form method="POST">
                            <div class="field">
                                <label class="label" for="username">
                                    <?= $this->text('label.username') ?>
                                </label>
                                <div class="control">
                                    <input class="input is-rounded" type="text" name="username" id="username" required value="<?= $this->getAppEnv() === 'dev' ? 'admin' : '' ?>">
                                </div>
                            </div>

                            <div class="field">
                                <label class="label" for="password">
                                    <?= $this->text('label.password') ?>
                                </label>
                                <div class="control">
                                    <input class="input is-rounded" type="password" name="password" id="password" required value="<?= $this->getAppEnv() === 'dev' ? 'Password12345' : '' ?>">
                                </div>
                            </div>

                            <div class="control">
                                <button class="button is-danger is-rounded">
                                    <?= $this->text('text.login') ?>
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
