<?php declare(strict_types=1); ?>
<?php /** @var Jesperbeisner\Fwstats\Service\ViewRenderService $this */ ?>
<!doctype html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/vnd.microsoft.icon" href="/img/favicon.ico">

    <link href="/css/bulma.min.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">

    <script src="/js/script.js" defer></script>

    <title><?= $this->getTitle(); ?></title>
</head>
<body>

<?php require __DIR__ . '/navigation.phtml' ?>

<main class="container">
    <?= $content ?>
</main>
</body>
</html>
