<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\Helper\Html;
use Jesperbeisner\Fwstats\Model\Player;
use Jesperbeisner\Fwstats\Service\RenderService;

/** @var RenderService $this */
/** @var array<array{world: string, id: int, name: string, race: string, xp: int, soul_xp: int, total_xp: int, profession: null|string, clan_id: null|int, clan_name: null|string, clan_shortcut: null|string}> $players */
/** @var int $page */

?>
<div class="table-container">
    <table class="table is-hoverable is-fullwidth">
        <thead>
        <tr>
            <td>#</td>
            <td>Name</td>
            <td>Rasse</td>
            <td class="has-text-centered">Clan</td>
            <td>Beruf</td>
            <td class="has-text-right">Xp</td>
            <td class="has-text-right">Seelen-Xp</td>
            <td class="has-text-right">Total-Xp</td>
            <td class="has-text-centered">Seelenstufe</td>
            <td class="has-text-right"></td>
        </tr>
        </thead>
        <tbody>
        <?php $i = ($page * 100) - 99; ?>
        <?php foreach ($players as $player): ?>
            <tr>
                <td>
                    <?= $i ?>
                </td>
                <td title="<?= Html::escape($player['name']) ?>">
                    <a href="/profile/<?= $player['world'] ?>/<?= $player['id'] ?>">
                        <?= Html::shortNames(Html::escape($player['name'])) ?>
                    </a>
                </td>
                <td>
                    <?= Html::escape($player['race']) ?>
                </td>
                <td class="has-text-centered">
                    <?php if ($player['clan_id'] === null): ?>
                        -
                    <?php else: ?>
                        <a
                            title="<?= Html::escape($player['clan_name']) ?>"
                            href="https://<?= $player['world'] ?>.freewar.de/freewar/internal/fight.php?action=watchclan&act_clan_id=<?= $player['clan_id'] ?>"
                            target="_blank"
                            class="clan_profile_link"
                        >
                            <?= Html::escape($player['clan_shortcut']) ?>
                        </a>
                    <?php endif; ?>
                </td>
                <td>
                    <?= $player['profession'] === null ? '-' : Html::escape($player['profession']) ?>
                </td>
                <td class="has-text-right">
                    <?= Html::numberFormat($player['xp']) ?>
                </td>
                <td class="has-text-right">
                    <?= Html::numberFormat($player['soul_xp']) ?>
                </td>
                <td class="has-text-right">
                    <?= Html::numberFormat($player['total_xp']) ?>
                </td>
                <td class="has-text-centered">
                    <?= Player::getSoulLevel($player['xp'], $player['soul_xp']) ?? '-' ?>
                </td>
                <td class="has-text-right">
                    <a href="https://<?= $player['world'] ?>.freewar.de/freewar/internal/fight.php?action=watchuser&act_user_id=<?= $player['id'] ?>" target="_blank" class="player_profile_link">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" width="16" height="16" fill="currentColor">
                            <path d="M128 32H32C14.31 32 0 46.31 0 64v96c0 17.69 14.31 32 32 32s32-14.31 32-32V96h64c17.69 0 32-14.31 32-32S145.7 32 128 32zM416 32h-96c-17.69 0-32 14.31-32 32s14.31 32 32 32h64v64c0 17.69 14.31 32 32 32s32-14.31 32-32V64C448 46.31 433.7 32 416 32zM128 416H64v-64c0-17.69-14.31-32-32-32s-32 14.31-32 32v96c0 17.69 14.31 32 32 32h96c17.69 0 32-14.31 32-32S145.7 416 128 416zM416 320c-17.69 0-32 14.31-32 32v64h-64c-17.69 0-32 14.31-32 32s14.31 32 32 32h96c17.69 0 32-14.31 32-32v-96C448 334.3 433.7 320 416 320z"/></svg>
                    </a>
                </td>
            </tr>
            <?php $i++ ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
