<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\Service\RenderService;

/** @var RenderService $this */
/** @var array<string, mixed> $vars */

/** @var int $page */
$page = $vars['page'];

/** @var bool $hasPreviousSite */
$hasPreviousSite = $vars['hasPreviousSite'];

/** @var bool $hasNextSite */
$hasNextSite = $vars['hasNextSite'];

/** @var bool $availablePages */
$availablePages = $vars['availablePages'];

$this->setTitle('Index');

?>
<div id="ranking">
    <div class="tabs is-centered is-medium mt-0">
        <ul class="m-0 p-0">
            <li id="action-freewar-tab"><a>ActionFreewar</a></li>
            <li id="chaos-freewar-tab"><a>ChaosFreewar</a></li>
        </ul>
    </div>
    <div>
        <div id="action-freewar-tab-content">
            <?php
            /** @var array<array{world: string, id: int, name: string, race: string, xp: int, soul_xp: int, total_xp: int, profession: null|string, clan_id: null|int, clan_name: null|string, clan_shortcut: null|string}> $players */
            $players = $vars['afsrvPlayers'];

            require __DIR__ . '/_ranking-table.phtml'
            ?>
        </div>
        <div id="chaos-freewar-tab-content" class="is-hidden">
            <?php
            /** @var array<array{world: string, id: int, name: string, race: string, xp: int, soul_xp: int, total_xp: int, profession: null|string, clan_id: null|int, clan_name: null|string, clan_shortcut: null|string}> $players */
            $players = $vars['chaosPlayers'];

            require __DIR__ . '/_ranking-table.phtml'
            ?>
        </div>
    </div>

    <div class="pagination is-centered mt-3 mb-0" aria-label="pagination">
        <?php if ($hasPreviousSite === true): ?>
            <a class="pagination-previous" href="/?page=<?= $page - 1 ?>">Vorherige Seite</a>
        <?php else: ?>
            <a class="pagination-previous is-disabled">Vorherige Seite</a>
        <?php endif; ?>

        <ul class="pagination-list">
            <li>
                Seite <?= $page . ' / ' . $availablePages ?>
            </li>
        </ul>

        <?php if ($hasNextSite === true): ?>
            <a class="pagination-next" href="/?page=<?= $page + 1 ?>">Nächste Seite</a>
        <?php else: ?>
            <a class="pagination-next is-disabled">Nächste Seite</a>
        <?php endif; ?>
    </div>
</div>
