<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\Model\Clan;
use Jesperbeisner\Fwstats\Model\Player;
use Jesperbeisner\Fwstats\Service\RenderService;

/** @var RenderService $this */
/** @var array<string, mixed> $vars */

/** @var string|null $loginText */
$loginText = $vars['login'];

/** @var string|null $logoutText */
$logoutText = $vars['logout'];

$this->setTitle('Index');

?>
<div id="ranking" class="mb-5">
    <div class="tabs is-centered is-medium">
        <ul>
            <li class="is-active" id="action-freewar-tab"><a>ActionFreewar</a></li>
            <li id="chaos-freewar-tab"><a>ChaosFreewar</a></li>
        </ul>
    </div>
    <div>
        <div id="action-freewar-tab-content">
            <?php
            /** @var Player[] $players */
            $players = $vars['afsrvPlayers'];

            /** @var Clan[] $clans */
            $clans = $vars['afsrvClans'];

            require __DIR__ . '/_ranking-table.phtml'
            ?>
        </div>
        <div id="chaos-freewar-tab-content" class="is-hidden">
            <?php
            /** @var Player[] $players */
            $players = $vars['chaosPlayers'];

            /** @var Clan[] $clans */
            $clans = $vars['chaosClans'];

            require __DIR__ . '/_ranking-table.phtml'
            ?>
        </div>
    </div>
</div>
