<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\DTO\Playtime;
use Jesperbeisner\Fwstats\Service\RenderService;

/** @var RenderService $this */
/** @var array<string, mixed> $vars */

$this->setTitle('title.playtime');

/** @var Playtime[] $afsrvPlaytime */
$afsrvPlaytime = $vars['afsrvPlaytime'];

/** @var Playtime[] $chaosPlaytime */
$chaosPlaytime = $vars['chaosPlaytime'];

?>
<main class="container mt-0 mb-5">
    <h1 class="is-size-1">
        <?= $this->text('title.playtime') ?>
    </h1>
    <div class="card">
        <div class="card-content">
            <div class="content">
                <div id="playtime">
                    <div class="tabs is-centered is-medium">
                        <ul>
                            <li class="is-active" id="action-freewar-tab"><a>ActionFreewar</a></li>
                            <li id="chaos-freewar-tab"><a>ChaosFreewar</a></li>
                        </ul>
                    </div>
                    <div>
                        <div id="action-freewar-tab-content">
                            <?php if ($afsrvPlaytime !== []): ?>
                                <?php $playtimes = $afsrvPlaytime ?>
                                <?php require __DIR__ . '/_playtime-table.phtml' ?>
                            <?php else: ?>
                                <p class="has-text-centered">
                                    <?= $this->text('text.no-playtimes-for-world-available', ['%WORLD%' => 'ActionFreewar']) ?>
                                </p>
                            <?php endif; ?>
                        </div>
                        <div id="chaos-freewar-tab-content" class="is-hidden">
                            <?php if ($chaosPlaytime !== []): ?>
                                <?php $playtimes = $chaosPlaytime ?>
                                <?php require __DIR__ . '/_playtime-table.phtml' ?>
                            <?php else: ?>
                                <p class="has-text-centered">
                                    <?= $this->text('text.no-playtimes-for-world-available', ['%WORLD%' => 'ChaosFreewar']) ?>
                                </p>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
