<?php declare(strict_types=1);

use Jesperbeisner\Fwstats\Helper\View; ?>
<?php /** @var Jesperbeisner\Fwstats\Service\ViewRenderService $this */ ?>
<?php $this->setTitle('Home'); ?>

<h2>
    Ranking
</h2>

<div class="content">
    <table>
        <thead>
        <tr>
            <td>#</td>
            <td>Name</td>
            <td>Rasse</td>
            <td>Beruf</td>
            <td class="text-end">Xp</td>
            <td class="text-end">Seelen-Xp</td>
            <td class="text-end">Total-Xp</td>
            <td class="text-end"></td>
        </tr>
        </thead>
        <tbody>
        <?php $i = 1; ?>
        <?php foreach ($this->vars['players'] as $player): ?>
            <tr>
                <td>
                    <?= $i ?>
                </td>
                <td>
                    <?= View::shortNames(View::escape($player['name'])) ?>
                </td>
                <td>
                    <?= $player['race'] ?>
                </td>
                <td>
                    <?= $player['profession'] === '' ? '-' : $player['profession'] ?>
                </td>
                <td class="text-end">
                    <?= View::numberFormat($player['xp']) ?>
                </td>
                <td class="text-end">
                    <?= View::numberFormat($player['soulXp']) ?>
                </td>
                <td class="text-end">
                    <?= View::numberFormat($player['totalXp']) ?>
                </td>
                <td class="text-end">
                    <a href="https://afsrv.freewar.de/freewar/internal/fight.php?action=watchuser&act_user_id=<?= $player['playerId'] ?>" target="_blank" class="player_profile_link">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" width="16" height="16" fill="currentColor">
                            <path d="M128 32H32C14.31 32 0 46.31 0 64v96c0 17.69 14.31 32 32 32s32-14.31 32-32V96h64c17.69 0 32-14.31 32-32S145.7 32 128 32zM416 32h-96c-17.69 0-32 14.31-32 32s14.31 32 32 32h64v64c0 17.69 14.31 32 32 32s32-14.31 32-32V64C448 46.31 433.7 32 416 32zM128 416H64v-64c0-17.69-14.31-32-32-32s-32 14.31-32 32v96c0 17.69 14.31 32 32 32h96c17.69 0 32-14.31 32-32S145.7 416 128 416zM416 320c-17.69 0-32 14.31-32 32v64h-64c-17.69 0-32 14.31-32 32s14.31 32 32 32h96c17.69 0 32-14.31 32-32v-96C448 334.3 433.7 320 416 320z"/></svg>
                    </a>
                </td>
            </tr>
            <?php $i++ ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
