<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\DTO\Clan;
use Jesperbeisner\Fwstats\DTO\Player;
use Jesperbeisner\Fwstats\Helper\View;

/** @var Jesperbeisner\Fwstats\Service\ViewRenderService $this */

$this->setTitle('Home');

/** @var Player[] $afsrvPlayers */
$afsrvPlayers = $this->vars['afsrvPlayers'];

/** @var Clan[] $afsrvClans */
$afsrvClans = $this->vars['afsrvClans'];

/** @var Player[] $chaosPlayers */
$chaosPlayers = $this->vars['chaosPlayers'];

/** @var Clan[] $chaosClans */
$chaosClans = $this->vars['chaosClans'];

?>
<div id="ranking" class="mb-5">
    <div class="tabs is-centered is-medium">
        <ul>
            <li class="is-active" id="action-freewar-tab"><a>ActionFreewar</a></li>
            <li id="chaos-freewar-tab"><a>ChaosFreewar</a></li>
        </ul>
    </div>
    <div>
        <div id="action-freewar-tab-content">
            <div class="table-container">
                <table class="table is-hoverable is-fullwidth">
                    <thead>
                    <tr>
                        <td>#</td>
                        <td>Name</td>
                        <td>Rasse</td>
                        <td class="has-text-centered">Clan</td>
                        <td>Beruf</td>
                        <td class="has-text-right">Xp</td>
                        <td class="has-text-right">Seelen-Xp</td>
                        <td class="has-text-right">Total-Xp</td>
                        <td class="has-text-centered">Seelenstufe</td>
                        <td class="has-text-right"></td>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i = 1; ?>
                    <?php foreach ($afsrvPlayers as $player): ?>
                        <tr>
                            <td>
                                <?= $i ?>
                            </td>
                            <td title="<?= View::escape($player->name) ?>">
                                <?= View::shortNames(View::escape($player->name)) ?>
                            </td>
                            <td>
                                <?= View::escape($player->race) ?>
                            </td>
                            <td class="has-text-centered">
                                <?php $clan = $afsrvClans[$player->clanId] ?? null; ?>
                                <?php if ($clan === null): ?>
                                    -
                                <?php else: ?>
                                    <a
                                            title="<?= View::escape($clan->name) ?>"
                                            href="https://afsrv.freewar.de/freewar/internal/fight.php?action=watchclan&act_clan_id=<?= $clan->clanId ?>"
                                    >
                                        <?= View::escape($clan->shortcut) ?>
                                    </a>
                                <?php endif; ?>
                            </td>
                            <td>
                                <?= $player->profession === null ? '-' : View::escape($player->profession) ?>
                            </td>
                            <td class="has-text-right">
                                <?= View::numberFormat($player->xp) ?>
                            </td>
                            <td class="has-text-right">
                                <?= View::numberFormat($player->soulXp) ?>
                            </td>
                            <td class="has-text-right">
                                <?= View::numberFormat($player->totalXp) ?>
                            </td>
                            <td class="has-text-centered">
                                <?= View::calculateSoulLevel($player) ?? '-' ?>
                            </td>
                            <td class="has-text-right">
                                <a href="https://afsrv.freewar.de/freewar/internal/fight.php?action=watchuser&act_user_id=<?= $player->playerId ?>" target="_blank" class="player_profile_link">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" width="16" height="16" fill="currentColor">
                                        <path d="M128 32H32C14.31 32 0 46.31 0 64v96c0 17.69 14.31 32 32 32s32-14.31 32-32V96h64c17.69 0 32-14.31 32-32S145.7 32 128 32zM416 32h-96c-17.69 0-32 14.31-32 32s14.31 32 32 32h64v64c0 17.69 14.31 32 32 32s32-14.31 32-32V64C448 46.31 433.7 32 416 32zM128 416H64v-64c0-17.69-14.31-32-32-32s-32 14.31-32 32v96c0 17.69 14.31 32 32 32h96c17.69 0 32-14.31 32-32S145.7 416 128 416zM416 320c-17.69 0-32 14.31-32 32v64h-64c-17.69 0-32 14.31-32 32s14.31 32 32 32h96c17.69 0 32-14.31 32-32v-96C448 334.3 433.7 320 416 320z"/></svg>
                                </a>
                            </td>
                        </tr>
                        <?php $i++ ?>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
        <div id="chaos-freewar-tab-content" class="is-hidden">
            <div class="table-container">
                <table class="table is-hoverable is-fullwidth">
                    <thead>
                    <tr>
                        <td>#</td>
                        <td>Name</td>
                        <td>Rasse</td>
                        <td class="has-text-centered">Clan</td>
                        <td>Beruf</td>
                        <td class="has-text-right">Xp</td>
                        <td class="has-text-right">Seelen-Xp</td>
                        <td class="has-text-right">Total-Xp</td>
                        <td class="has-text-centered">Seelenstufe</td>
                        <td class="has-text-right"></td>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i = 1; ?>
                    <?php foreach ($chaosPlayers as $player): ?>
                        <tr>
                            <td>
                                <?= $i ?>
                            </td>
                            <td title="<?= View::escape($player->name) ?>">
                                <?= View::shortNames(View::escape($player->name)) ?>
                            </td>
                            <td>
                                <?= View::escape($player->race) ?>
                            </td>
                            <td class="has-text-centered">
                                <?php $clan = $chaosClans[$player->clanId] ?? null; ?>
                                <?php if ($clan === null): ?>
                                    -
                                <?php else: ?>
                                    <a
                                            title="<?= View::escape($clan->name) ?>"
                                            href="https://chaos.freewar.de/freewar/internal/fight.php?action=watchclan&act_clan_id=<?= $clan->clanId ?>"
                                    >
                                        <?= View::escape($clan->shortcut) ?>
                                    </a>
                                <?php endif; ?>
                            </td>
                            <td>
                                <?= $player->profession === null ? '-' : View::escape($player->profession) ?>
                            </td>
                            <td class="has-text-right">
                                <?= View::numberFormat($player->xp) ?>
                            </td>
                            <td class="has-text-right">
                                <?= View::numberFormat($player->soulXp) ?>
                            </td>
                            <td class="has-text-right">
                                <?= View::numberFormat($player->totalXp) ?>
                            </td>
                            <td class="has-text-centered">
                                <?= View::calculateSoulLevel($player) ?? '-' ?>
                            </td>
                            <td class="has-text-right">
                                <a href="https://afsrv.freewar.de/freewar/internal/fight.php?action=watchuser&act_user_id=<?= $player->playerId ?>" target="_blank" class="player_profile_link">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" width="16" height="16" fill="currentColor">
                                        <path d="M128 32H32C14.31 32 0 46.31 0 64v96c0 17.69 14.31 32 32 32s32-14.31 32-32V96h64c17.69 0 32-14.31 32-32S145.7 32 128 32zM416 32h-96c-17.69 0-32 14.31-32 32s14.31 32 32 32h64v64c0 17.69 14.31 32 32 32s32-14.31 32-32V64C448 46.31 433.7 32 416 32zM128 416H64v-64c0-17.69-14.31-32-32-32s-32 14.31-32 32v96c0 17.69 14.31 32 32 32h96c17.69 0 32-14.31 32-32S145.7 416 128 416zM416 320c-17.69 0-32 14.31-32 32v64h-64c-17.69 0-32 14.31-32 32s14.31 32 32 32h96c17.69 0 32-14.31 32-32v-96C448 334.3 433.7 320 416 320z"/></svg>
                                </a>
                            </td>
                        </tr>
                        <?php $i++ ?>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
