<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\Service\RenderService;

/** @var RenderService $this */

?>
<footer id="site-footer" class="has-background-dark">
    <?php if ($this->getSession()->getUser() === null): ?>
        <a href="/login">
            <?= $this->text('text.login') ?>
        </a>
    <?php else: ?>
        <a href="/logout">
            <?= $this->text('text.logout') ?>
        </a>
    <?php endif; ?>
</footer>
