<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\Service\RenderService;

/** @var RenderService $this */
/** @var string $content */

?>
<!doctype html>
<html lang="<?= $this->translator->getLocale()->value ?>">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link type="text/plain" rel="author" href="/humans.txt">
    <link type="image/png" rel="icon" href="/img/favicon.png">
    <link type="text/css" rel="stylesheet" href="/css/bulma.min.css">
    <link type="text/css" rel="stylesheet" href="/css/style.css">
    <script type="text/javascript" src="/js/script.js"></script>
    <script defer data-domain="fwstats.de" src="https://plausible.io/js/script.js"></script>
    <title><?= $this->getTitle(); ?></title>
</head>
<body>
    <?php require __DIR__ . '/navigation.phtml' ?>

    <?php require __DIR__ . '/flash-message.phtml' ?>

    <?= $content ?>

    <?php require __DIR__ . '/footer.phtml' ?>
</body>
</html>
