<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\Enum\FlashEnum;
use Jesperbeisner\Fwstats\Service\RenderService;

/** @var RenderService $this */
/** @var string $content */

?>
<!doctype html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="/img/favicon.png"/>
    <link href="/css/bulma.min.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">
    <script src="/js/script.js" defer></script>
    <title><?= $this->getTitle(); ?></title>
</head>
<body>
    <?php require __DIR__ . '/navigation.phtml' ?>

    <main class="container">
        <?php if ([] !== $successFlashMessages = $this->session->getFlash(FlashEnum::SUCCESS)): ?>
            <article class="message is-success has-text-centered info-text">
                <div class="message-body">
                    <?php foreach ($successFlashMessages as $successFlashMessage): ?>
                        <p><?= $successFlashMessage ?></p>
                    <?php endforeach; ?>
                </div>
            </article>
        <?php endif; ?>

        <?php if ([] !== $errorFlashMessages = $this->session->getFlash(FlashEnum::ERROR)): ?>
            <article class="message is-danger has-text-centered info-text">
                <div class="message-body">
                    <?php foreach ($errorFlashMessages as $errorFlashMessage): ?>
                        <p><?= $errorFlashMessage ?></p>
                    <?php endforeach; ?>
                </div>
            </article>
        <?php endif; ?>

        <?= $content ?>
    </main>

    <?php require __DIR__ . '/footer.phtml' ?>
</body>
</html>
