<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\Service\RenderService;

/** @var RenderService $this */
/** @var string $content */

?>
<!doctype html>
<html lang="<?= $this->translator->getLocale()->value ?>">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="/img/favicon.png"/>
    <link href="/css/bulma.min.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">
    <script src="/js/script.js" defer></script>
    <title><?= $this->getTitle(); ?></title>
</head>
<body>
    <?php require __DIR__ . '/navigation.phtml' ?>

    <?php require __DIR__ . '/flash-message.phtml' ?>

    <?= $content ?>

    <?php require __DIR__ . '/footer.phtml' ?>
</body>
</html>
