<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\Enum\LocaleEnum;
use Jesperbeisner\Fwstats\Service\RenderService;

/** @var RenderService $this */

?>
<header>
    <nav id="navbar" class="navbar is-dark" role="navigation" aria-label="main navigation">
        <div class="container">
            <div class="navbar-brand">
                <a class="navbar-item" href="/">
                    <img src="/img/website-logo.png" class="mr-2">
                    <h1 class="title is-4 has-text-danger">FWSTATS</h1>
                </a>
                <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbar-menu">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>
            <div id="navbar-menu" class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item" href="/">
                        <?= $this->text('navigation.index') ?>
                    </a>
                    <a class="navbar-item" href="/playtime">
                        <?= $this->text('navigation.playtime') ?>
                    </a>
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link">
                            <?= $this->text('navigation.changes') ?>
                        </a>
                        <div class="navbar-dropdown">
                            <a class="navbar-item" href="/changes/names">
                                <?= $this->text('navigation.changes.names') ?>
                            </a>
                        </div>
                    </div>
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link">
                            <?= $this->text('navigation.pictures') ?>
                        </a>
                        <div class="navbar-dropdown">
                            <a class="navbar-item" href="/images/ranking">
                                <?= $this->text('navigation.pictures.ranking') ?>
                            </a>
                        </div>
                    </div>
                    <?php if ($this->getSession()->getUser() !== null): ?>
                        <a class="navbar-item" href="/admin">
                            <?= $this->text('navigation.admin') ?>
                        </a>
                    <?php endif; ?>
                </div>
                <div class="navbar-end">
                    <div class="navbar-item">
                        <form action="/search" method="GET">
                            <div class="field has-addons">
                                <div class="control">
                                    <label for="query" aria-hidden="true" style="display: none"><?= $this->text('label.search') ?>></label>
                                    <input class="input is-rounded" type="text" name="query" id="query" placeholder="…" value="<?= $this->getRequest()->getGetParameter('query') ?? '' ?>" required>
                                </div>
                                <div class="control">
                                    <button class="button is-danger is-rounded">
                                        <?= $this->text('navigation.search') ?>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="navbar-item">
                        <?php if ($this->translator->getLocale() !== LocaleEnum::EN): ?>
                            <a id="english-icon" href="/locale?locale=en" title="<?= $this->text('hover.change-language-to-english') ?>">
                                <img src="/img/english-icon.png" alt="<?= $this->text('alt.english-flag') ?>">
                            </a>
                        <?php endif; ?>
                        <?php if ($this->translator->getLocale() !== LocaleEnum::DE): ?>
                            <a id="german-icon" href="/locale?locale=de" title="<?= $this->text('hover.change-language-to-german') ?>">
                                <img src="/img/german-icon.png" alt="<?= $this->text('alt.german-flag') ?>">
                            </a>
                        <?php endif; ?>
                    </div>
                    <div class="navbar-item">
                        <a id="github-logo" href="https://github.com/jesperbeisner/fwstats.de" title="<?= $this->text('hover.look-at-the-source-code-of-this-website-on-github') ?>">
                            <svg xmlns="http://www.w3.org/2000/svg" class="github_logo" width="32" height="32" fill="currentColor" viewBox="0 0 16 16">
                                <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>
