<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\Service\RenderService;

/** @var RenderService $this */
/** @var array<string, mixed> $vars */

$this->setTitle('title.xp');

/** @var array<array{world: string, player_id: int, name: string, xp: int, soul_xp: int, total_xp: int, xp_changes: int}> $afsrvXpChanges */
$afsrvXpChanges = $vars['afsrvXpChanges'];

/** @var array<array{world: string, player_id: int, name: string, xp: int, soul_xp: int, total_xp: int, xp_changes: int}> $chaosXpChanges */
$chaosXpChanges = $vars['chaosXpChanges'];

?>
<main class="container mt-0 mb-5">
    <h1 class="is-size-1">
        <?= $this->text('title.xp') ?>
    </h1>
    <div class="card">
        <div class="card-content">
            <div class="content">
                <div id="playtime">
                    <div class="tabs is-centered is-medium">
                        <ul>
                            <li class="is-active" id="action-freewar-tab"><a>ActionFreewar</a></li>
                            <li id="chaos-freewar-tab"><a>ChaosFreewar</a></li>
                        </ul>
                    </div>
                    <div>
                        <div id="action-freewar-tab-content">
                            <?php if ($afsrvXpChanges !== []): ?>
                                <?php $xpChanges = $afsrvXpChanges ?>
                                <?php require __DIR__ . '/_xp-table.phtml' ?>
                            <?php else: ?>
                                <p class="has-text-centered">
                                    <?= $this->text('text.no-xp-changes-for-world-available', ['%WORLD%' => 'ActionFreewar']) ?>
                                </p>
                            <?php endif; ?>
                        </div>
                        <div id="chaos-freewar-tab-content" class="is-hidden">
                            <?php if ($chaosXpChanges !== []): ?>
                                <?php $xpChanges = $chaosXpChanges ?>
                                <?php require __DIR__ . '/_xp-table.phtml' ?>
                            <?php else: ?>
                                <p class="has-text-centered">
                                    <?= $this->text('text.no-xp-changes-for-world-available', ['%WORLD%' => 'ChaosFreewar']) ?>
                                </p>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
