<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\Model\Log;
use Jesperbeisner\Fwstats\Service\RenderService;

/** @var RenderService $this */
/** @var array<string, mixed> $vars */

/** @var Log[] $logs */
$logs = $vars['logs'];

$this->setTitle('Logs');

?>
<div class="table-container">
    <table class="table is-hoverable is-fullwidth">
        <thead>
        <tr>
            <td>#</td>
            <td>Url</td>
            <td>Datum</td>
        </tr>
        </thead>
        <tbody>
        <?php $i = 1; ?>
        <?php foreach ($logs as $log): ?>
            <tr>
                <td><?= $i ?></td>
                <td><a href="<?= $log->url ?>" target="_blank"><?= $log->url ?></a></td>
                <td><?= $log->created->format('d.m.Y H:i:s') ?></td>
            </tr>
        <?php $i++ ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
