<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\Model\Log;
use Jesperbeisner\Fwstats\Service\ViewRenderService;

/** @var ViewRenderService $this */

/** @var Log[] $logs */
$logs = $this->vars['logs'];

$this->setTitle('Logs');

?>
<div id="logs">
    <h1 class="title is-2">
        Logs
    </h1>
    <div class="card">
        <div class="card-content">
            <div class="content">
                <div class="table-container">
                    <table class="table is-hoverable is-fullwidth">
                        <thead>
                        <tr>
                            <td>#</td>
                            <td>Url</td>
                            <td>Datum</td>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $i = 1; ?>
                        <?php foreach ($logs as $log): ?>
                            <tr>
                                <td><?= $i ?></td>
                                <td><?= $log->url ?></td>
                                <td><?= $log->created->format('d.m.Y H:i:s') ?></td>
                            </tr>
                        <?php $i++ ?>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
