<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\Helper\Html;
use Jesperbeisner\Fwstats\Service\RenderService;

/** @var RenderService $this */
/** @var array<array{world: string, player_id: int, name: string, old_profession: null|string, new_profession: null|string, created: string}> $professionChanges */

?>
<div class="table-container">
    <table class="table is-hoverable is-fullwidth">
        <thead>
        <tr>
            <td>#</td>
            <td><?= $this->text('table.name') ?></td>
            <td><?= $this->text('table.old-profession') ?></td>
            <td><?= $this->text('table.new-profession') ?></td>
            <td class="has-text-centered"><?= $this->text('table.date') ?></td>
            <td class="has-text-right"></td>
        </tr>
        </thead>
        <tbody>
        <?php $i = 1; ?>
        <?php foreach ($professionChanges as $professionChange): ?>
            <tr>
                <td>
                    <?= $i ?>
                </td>
                <td title="<?= $this->escape($professionChange['name']) ?>">
                    <a href="/profile/<?= $this->escape($professionChange['world']) ?>/<?= $this->escape((string) $professionChange['player_id']) ?>">
                        <?= Html::shortNames($this->escape($professionChange['name'])) ?>
                    </a>
                </td>
                <td title="<?= $this->escape($professionChange['old_profession'] ?? '-') ?>">
                    <?= $this->escape($professionChange['old_profession'] ?? '-') ?>
                </td>
                <td title="<?= $this->escape($professionChange['new_profession'] ?? '-') ?>">
                    <?= $this->escape($professionChange['new_profession'] ?? '-') ?>
                </td>
                <td class="has-text-centered" title="<?= (new DateTimeImmutable($professionChange['created']))->format('d.m.Y H:i:s') ?>">
                    <?= (new DateTimeImmutable($professionChange['created']))->format('d.m.Y H:i:s') ?>
                </td>
                <td class="has-text-right">
                    <a href="https://<?= $this->escape($professionChange['world']) ?>.freewar.de/freewar/internal/fight.php?action=watchuser&act_user_id=<?= $this->escape((string) $professionChange['player_id']) ?>" target="_blank" class="player_profile_link">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" width="16" height="16" fill="currentColor">
                            <path d="M128 32H32C14.31 32 0 46.31 0 64v96c0 17.69 14.31 32 32 32s32-14.31 32-32V96h64c17.69 0 32-14.31 32-32S145.7 32 128 32zM416 32h-96c-17.69 0-32 14.31-32 32s14.31 32 32 32h64v64c0 17.69 14.31 32 32 32s32-14.31 32-32V64C448 46.31 433.7 32 416 32zM128 416H64v-64c0-17.69-14.31-32-32-32s-32 14.31-32 32v96c0 17.69 14.31 32 32 32h96c17.69 0 32-14.31 32-32S145.7 416 128 416zM416 320c-17.69 0-32 14.31-32 32v64h-64c-17.69 0-32 14.31-32 32s14.31 32 32 32h96c17.69 0 32-14.31 32-32v-96C448 334.3 433.7 320 416 320z"/>
                        </svg>
                    </a>
                </td>
            </tr>
            <?php $i++ ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
