<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\Model\PlayerNameHistory;
use Jesperbeisner\Fwstats\Service\RenderService;

/** @var RenderService $this */
/** @var array<string, mixed> $vars */

/** @var PlayerNameHistory[] $afsrvBansAndDeletions */
$afsrvBansAndDeletions = $vars['afsrvBansAndDeletions'];

/** @var PlayerNameHistory[] $chaosBansAndDeletions */
$chaosBansAndDeletions = $vars['chaosBansAndDeletions'];

$this->setTitle('title.bans-and-deletions-changes');

?>
<main class="container mt-0 mb-5">
    <h1 class="is-size-1">
        <?= $this->text('title.bans-and-deletions-changes') ?>
    </h1>
    <div class="card">
        <div class="card-content">
            <div class="content">
                <div id="name-change">
                    <div class="tabs is-centered is-medium">
                        <ul>
                            <li class="is-active" id="action-freewar-tab"><a>ActionFreewar</a></li>
                            <li id="chaos-freewar-tab"><a>ChaosFreewar</a></li>
                        </ul>
                    </div>
                    <div>
                        <div id="action-freewar-tab-content">
                            <?php if ($afsrvBansAndDeletions !== []): ?>
                                <?php $bansAndDeletions = $afsrvBansAndDeletions ?>
                                <?php require __DIR__ . '/_bans-and-deletions-table.phtml' ?>
                            <?php else: ?>
                                <p class="has-text-centered">
                                    <?= $this->text('text.no-bans-or-deletions-for-world-available', ['%WORLD%' => 'ActionFreewar']) ?>
                                </p>
                            <?php endif; ?>
                        </div>
                        <div id="chaos-freewar-tab-content" class="is-hidden">
                            <?php if ($chaosBansAndDeletions !== []): ?>
                                <?php $bansAndDeletions = $chaosBansAndDeletions ?>
                                <?php require __DIR__ . '/_bans-and-deletions-table.phtml' ?>
                            <?php else: ?>
                                <p class="has-text-centered">
                                    <?= $this->text('text.no-bans-or-deletions-for-world-available', ['%WORLD%' => 'ChaosFreewar']) ?>
                                </p>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
