<?php

declare(strict_types=1);

use Jesperbeisner\Fwstats\Service\RenderService;

/** @var RenderService $this */
/** @var array<string, mixed> $vars */

$this->setTitle('title.race-changes');

/** @var array<array{world: string, player_id: int, name: string, old_race: string, new_race: string, created: string}> $afsrvRaceChanges */
$afsrvRaceChanges = $vars['afsrvRaceChanges'];

/** @var array<array{world: string, player_id: int, name: string, old_race: string, new_race: string, created: string}> $chaosRaceChanges */
$chaosRaceChanges = $vars['chaosRaceChanges'];

?>
<main class="container mt-0 mb-5">
    <h1 class="is-size-1">
        <?= $this->text('title.race-changes') ?>
    </h1>
    <div class="card">
        <div class="card-content">
            <div class="content">
                <div id="race-change">
                    <div class="tabs is-centered is-medium">
                        <ul>
                            <li class="is-active" id="action-freewar-tab"><a>ActionFreewar</a></li>
                            <li id="chaos-freewar-tab"><a>ChaosFreewar</a></li>
                        </ul>
                    </div>
                    <div>
                        <div id="action-freewar-tab-content">
                            <?php if (count($afsrvRaceChanges) > 0): ?>
                                <?php $raceChanges = $afsrvRaceChanges ?>
                                <?php require __DIR__ . '/_race-changes-table.phtml' ?>
                            <?php else: ?>
                                <p class="has-text-centered">
                                    <?= $this->text('text.no-race-changes-for-world-available', ['%WORLD%' => 'ActionFreewar']) ?>
                                </p>
                            <?php endif; ?>
                        </div>
                        <div id="chaos-freewar-tab-content" class="is-hidden">
                            <?php if (count($chaosRaceChanges) > 0): ?>
                                <?php $raceChanges = $chaosRaceChanges ?>
                                <?php require __DIR__ . '/_race-changes-table.phtml' ?>
                            <?php else: ?>
                                <p class="has-text-centered">
                                    <?= $this->text('text.no-race-changes-for-world-available', ['%WORLD%' => 'ChaosFreewar']) ?>
                                </p>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
