name: Action

on: [push]

jobs:
  testing:
    name: Run PHP-CS-Fixer, PHPUnit and PHPStan
    runs-on: ubuntu-22.04

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
          ini-values: "memory_limit=-1"
        env:
          fail-fast: true

      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: composer install

      - name: Run Full Testsuite
        run: composer test

  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    needs: testing

    steps:
      - name: Run the deployment script
        uses: appleboy/ssh-action@master
        if: github.ref_name == 'master'
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          scripts: echo 'hello world'
          #script: /bin/bash ./deployments/scripts/fwstats.sh
