name: Deployment

on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    needs: testing

    steps:
      - name: Run the deployment script
        uses: appleboy/ssh-action@master
        if: github.ref_name == 'master'
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          #script: /bin/bash ./deployments/scripts/fwstats.sh
          script: echo Hello world